# Generated by Django 4.2.4 on 2023-08-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='airport.iata', to_field='iata_code'),
        ),
    ]
